/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.tipo_medicamento.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.entity.Tipo_MedicamentoEntity;

public abstract class _Tipo_MedicamentoConverter {

	public static Tipo_MedicamentoDTO entity2PersistenceDTO(Tipo_MedicamentoEntity entity){
		if (entity != null) {
			Tipo_MedicamentoDTO dto = new Tipo_MedicamentoDTO();
					dto.setName(entity.getName());
					dto.setId(entity.getId());
					dto.setValor(entity.getValor());
			return dto;
		}else{
			return null;
		}
	}
	
	public static Tipo_MedicamentoEntity persistenceDTO2Entity(Tipo_MedicamentoDTO dto){
		if(dto!=null){
			Tipo_MedicamentoEntity entity=new Tipo_MedicamentoEntity();
					entity.setName(dto.getName());
			
					entity.setId(dto.getId());
			
					entity.setValor(dto.getValor());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<Tipo_MedicamentoDTO> entity2PersistenceDTOList(List<Tipo_MedicamentoEntity> entities){
		List<Tipo_MedicamentoDTO> dtos=new ArrayList<Tipo_MedicamentoDTO>();
		for(Tipo_MedicamentoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<Tipo_MedicamentoEntity> persistenceDTO2EntityList(List<Tipo_MedicamentoDTO> dtos){
		List<Tipo_MedicamentoEntity> entities=new ArrayList<Tipo_MedicamentoEntity>();
		for(Tipo_MedicamentoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}