/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.notadevoz.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G8.notadevoz.logic.dto.NotaDeVozDTO;
import co.edu.uniandes.csw.G8.notadevoz.logic.dto.NotaDeVozPageDTO;
import co.edu.uniandes.csw.G8.notadevoz.persistence.api._INotaDeVozPersistence;
import co.edu.uniandes.csw.G8.notadevoz.persistence.converter.NotaDeVozConverter;
import co.edu.uniandes.csw.G8.notadevoz.persistence.entity.NotaDeVozEntity;

public abstract class _NotaDeVozPersistence implements _INotaDeVozPersistence {

  	@PersistenceContext(unitName="MigrandesCrudPU")
 
	protected EntityManager entityManager;
	
	public NotaDeVozDTO createNotaDeVoz(NotaDeVozDTO notaDeVoz) {
		NotaDeVozEntity entity=NotaDeVozConverter.persistenceDTO2Entity(notaDeVoz);
		entityManager.persist(entity);
		return NotaDeVozConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<NotaDeVozDTO> getNotaDeVozs() {
		Query q = entityManager.createQuery("select u from NotaDeVozEntity u");
		return NotaDeVozConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public NotaDeVozPageDTO getNotaDeVozs(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from NotaDeVozEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from NotaDeVozEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		NotaDeVozPageDTO response = new NotaDeVozPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(NotaDeVozConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public NotaDeVozDTO getNotaDeVoz(Long id) {
		return NotaDeVozConverter.entity2PersistenceDTO(entityManager.find(NotaDeVozEntity.class, id));
	}

	public void deleteNotaDeVoz(Long id) {
		NotaDeVozEntity entity=entityManager.find(NotaDeVozEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateNotaDeVoz(NotaDeVozDTO detail) {
		NotaDeVozEntity entity=entityManager.merge(NotaDeVozConverter.persistenceDTO2Entity(detail));
		NotaDeVozConverter.entity2PersistenceDTO(entity);
	}

}