/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.dolor.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.dolor.logic.dto.DolorPageDTO;
import co.edu.uniandes.csw.G8.dolor.logic.dto.DolorDTO;
import co.edu.uniandes.csw.G8.dolor.logic.api.IDolorLogicService;
import co.edu.uniandes.csw.G8.dolor.persistence.DolorPersistence;
import co.edu.uniandes.csw.G8.dolor.persistence.api.IDolorPersistence;
import co.edu.uniandes.csw.G8.dolor.persistence.entity.DolorEntity;
import co.edu.uniandes.csw.G8.dolor.persistence.converter.DolorConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class DolorLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(DolorLogicService.class.getPackage())
				.addPackage(IDolorLogicService.class.getPackage())
				.addPackage(DolorPersistence.class.getPackage())
				.addPackage(DolorEntity.class.getPackage())
				.addPackage(IDolorPersistence.class.getPackage())
                .addPackage(DolorDTO.class.getPackage())
                .addPackage(DolorConverter.class.getPackage())
                .addPackage(DolorEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IDolorLogicService dolorLogicService;
	
	@Inject
	private IDolorPersistence dolorPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<DolorDTO> dtos=dolorPersistence.getDolors();
		for(DolorDTO dto:dtos){
			dolorPersistence.deleteDolor(dto.getId());
		}
	}

	private List<DolorDTO> data=new ArrayList<DolorDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			DolorDTO pdto=new DolorDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setIntensidadId(generateRandom(Long.class));
			pdto=dolorPersistence.createDolor(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createDolorTest(){
		DolorDTO ldto=new DolorDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setIntensidadId(generateRandom(Long.class));
		
		
		DolorDTO result=dolorLogicService.createDolor(ldto);
		
		Assert.assertNotNull(result);
		
		DolorDTO pdto=dolorPersistence.getDolor(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getIntensidadId(), pdto.getIntensidadId());	
	}
	
	@Test
	public void getDolorsTest(){
		List<DolorDTO> list=dolorLogicService.getDolors();
		Assert.assertEquals(list.size(), data.size());
        for(DolorDTO ldto:list){
        	boolean found=false;
            for(DolorDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getDolorTest(){
		DolorDTO pdto=data.get(0);
		DolorDTO ldto=dolorLogicService.getDolor(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getIntensidadId(), ldto.getIntensidadId());
        
	}
	
	@Test
	public void deleteDolorTest(){
		DolorDTO pdto=data.get(0);
		dolorLogicService.deleteDolor(pdto.getId());
        DolorDTO deleted=dolorPersistence.getDolor(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateDolorTest(){
		DolorDTO pdto=data.get(0);
		
		DolorDTO ldto=new DolorDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setIntensidadId(generateRandom(Long.class));
		
		
		dolorLogicService.updateDolor(ldto);
		
		
		DolorDTO resp=dolorPersistence.getDolor(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getIntensidadId(), resp.getIntensidadId());	
	}
	
	@Test
	public void getDolorPaginationTest(){
		
		DolorPageDTO dto1=dolorLogicService.getDolors(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		DolorPageDTO dto2=dolorLogicService.getDolors(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(DolorDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(DolorDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(DolorDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(DolorDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        DolorPageDTO dto3=dolorLogicService.getDolors(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(DolorDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(DolorDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}