/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.episodio.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioDTO;
import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioPageDTO;
import co.edu.uniandes.csw.G8.episodio.persistence.api._IEpisodioPersistence;
import co.edu.uniandes.csw.G8.episodio.persistence.converter.EpisodioConverter;
import co.edu.uniandes.csw.G8.episodio.persistence.entity.EpisodioEntity;

public abstract class _EpisodioPersistence implements _IEpisodioPersistence {

  	@PersistenceContext(unitName="MigrandesCrudPU")
 
	protected EntityManager entityManager;
	
	public EpisodioDTO createEpisodio(EpisodioDTO episodio) {
		EpisodioEntity entity=EpisodioConverter.persistenceDTO2Entity(episodio);
		entityManager.persist(entity);
		return EpisodioConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<EpisodioDTO> getEpisodios() {
		Query q = entityManager.createQuery("select u from EpisodioEntity u");
		return EpisodioConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public EpisodioPageDTO getEpisodios(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from EpisodioEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from EpisodioEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		EpisodioPageDTO response = new EpisodioPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(EpisodioConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public EpisodioDTO getEpisodio(Long id) {
		return EpisodioConverter.entity2PersistenceDTO(entityManager.find(EpisodioEntity.class, id));
	}

	public void deleteEpisodio(Long id) {
		EpisodioEntity entity=entityManager.find(EpisodioEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateEpisodio(EpisodioDTO detail) {
		EpisodioEntity entity=entityManager.merge(EpisodioConverter.persistenceDTO2Entity(detail));
		EpisodioConverter.entity2PersistenceDTO(entity);
	}

}