/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.intensidad.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadPageDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.api.IIntensidadLogicService;
import co.edu.uniandes.csw.G8.intensidad.persistence.IntensidadPersistence;
import co.edu.uniandes.csw.G8.intensidad.persistence.api.IIntensidadPersistence;
import co.edu.uniandes.csw.G8.intensidad.persistence.entity.IntensidadEntity;
import co.edu.uniandes.csw.G8.intensidad.persistence.converter.IntensidadConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class IntensidadLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(IntensidadLogicService.class.getPackage())
				.addPackage(IIntensidadLogicService.class.getPackage())
				.addPackage(IntensidadPersistence.class.getPackage())
				.addPackage(IntensidadEntity.class.getPackage())
				.addPackage(IIntensidadPersistence.class.getPackage())
                .addPackage(IntensidadDTO.class.getPackage())
                .addPackage(IntensidadConverter.class.getPackage())
                .addPackage(IntensidadEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IIntensidadLogicService intensidadLogicService;
	
	@Inject
	private IIntensidadPersistence intensidadPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<IntensidadDTO> dtos=intensidadPersistence.getIntensidads();
		for(IntensidadDTO dto:dtos){
			intensidadPersistence.deleteIntensidad(dto.getId());
		}
	}

	private List<IntensidadDTO> data=new ArrayList<IntensidadDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			IntensidadDTO pdto=new IntensidadDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setValor(generateRandom(Integer.class));
			pdto=intensidadPersistence.createIntensidad(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createIntensidadTest(){
		IntensidadDTO ldto=new IntensidadDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setValor(generateRandom(Integer.class));
		
		
		IntensidadDTO result=intensidadLogicService.createIntensidad(ldto);
		
		Assert.assertNotNull(result);
		
		IntensidadDTO pdto=intensidadPersistence.getIntensidad(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getValor(), pdto.getValor());	
	}
	
	@Test
	public void getIntensidadsTest(){
		List<IntensidadDTO> list=intensidadLogicService.getIntensidads();
		Assert.assertEquals(list.size(), data.size());
        for(IntensidadDTO ldto:list){
        	boolean found=false;
            for(IntensidadDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getIntensidadTest(){
		IntensidadDTO pdto=data.get(0);
		IntensidadDTO ldto=intensidadLogicService.getIntensidad(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getValor(), ldto.getValor());
        
	}
	
	@Test
	public void deleteIntensidadTest(){
		IntensidadDTO pdto=data.get(0);
		intensidadLogicService.deleteIntensidad(pdto.getId());
        IntensidadDTO deleted=intensidadPersistence.getIntensidad(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateIntensidadTest(){
		IntensidadDTO pdto=data.get(0);
		
		IntensidadDTO ldto=new IntensidadDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setValor(generateRandom(Integer.class));
		
		
		intensidadLogicService.updateIntensidad(ldto);
		
		
		IntensidadDTO resp=intensidadPersistence.getIntensidad(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getValor(), resp.getValor());	
	}
	
	@Test
	public void getIntensidadPaginationTest(){
		
		IntensidadPageDTO dto1=intensidadLogicService.getIntensidads(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		IntensidadPageDTO dto2=intensidadLogicService.getIntensidads(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(IntensidadDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(IntensidadDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(IntensidadDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(IntensidadDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        IntensidadPageDTO dto3=intensidadLogicService.getIntensidads(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(IntensidadDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(IntensidadDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}