/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.episodio.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioPageDTO;
import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioDTO;
import co.edu.uniandes.csw.G8.episodio.persistence.api.IEpisodioPersistence;
import co.edu.uniandes.csw.G8.episodio.persistence.entity.EpisodioEntity;
import co.edu.uniandes.csw.G8.episodio.persistence.converter.EpisodioConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class EpisodioPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(EpisodioPersistence.class.getPackage())
				.addPackage(EpisodioEntity.class.getPackage())
				.addPackage(IEpisodioPersistence.class.getPackage())
                .addPackage(EpisodioDTO.class.getPackage())
                .addPackage(EpisodioConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IEpisodioPersistence episodioPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from EpisodioEntity").executeUpdate();
	}

	private List<EpisodioEntity> data=new ArrayList<EpisodioEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			EpisodioEntity entity=new EpisodioEntity();
			entity.setName(generateRandom(String.class));
			entity.setFecha(generateRandom(Date.class));
			entity.setActividadId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createEpisodioTest(){
		EpisodioDTO dto=new EpisodioDTO();
		dto.setName(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setActividadId(generateRandom(Long.class));
		
		EpisodioDTO result=episodioPersistence.createEpisodio(dto);
		
		Assert.assertNotNull(result);
		
		EpisodioEntity entity=em.find(EpisodioEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
Assert.assertEquals(parseDate(dto.getFecha()), entity.getFecha());	
		Assert.assertEquals(dto.getActividadId(), entity.getActividadId());
	}
	
	@Test
	public void getEpisodiosTest(){
		List<EpisodioDTO> list=episodioPersistence.getEpisodios();
		Assert.assertEquals(list.size(), data.size());
        for(EpisodioDTO dto:list){
        	boolean found=false;
            for(EpisodioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getEpisodioTest(){
		EpisodioEntity entity=data.get(0);
		EpisodioDTO dto=episodioPersistence.getEpisodio(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getActividadId(), dto.getActividadId());
        
	}
	
	@Test
	public void deleteEpisodioTest(){
		EpisodioEntity entity=data.get(0);
		episodioPersistence.deleteEpisodio(entity.getId());
        EpisodioEntity deleted=em.find(EpisodioEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateEpisodioTest(){
		EpisodioEntity entity=data.get(0);
		
		EpisodioDTO dto=new EpisodioDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
dto.setFecha(generateRandomDate());
		dto.setActividadId(generateRandom(Long.class));
		
		
		episodioPersistence.updateEpisodio(dto);
		
		
		EpisodioEntity resp=em.find(EpisodioEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
Assert.assertEquals(parseDate(dto.getFecha()), resp.getFecha());
		Assert.assertEquals(dto.getActividadId(), resp.getActividadId());	
	}
	
	@Test
	public void getEpisodioPaginationTest(){
		//Page 1
		EpisodioPageDTO dto1=episodioPersistence.getEpisodios(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        EpisodioPageDTO dto2=episodioPersistence.getEpisodios(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(EpisodioDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(EpisodioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(EpisodioDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(EpisodioEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}