/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.medicamento.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoPageDTO;
import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoDTO;
import co.edu.uniandes.csw.G8.medicamento.persistence.api.IMedicamentoPersistence;
import co.edu.uniandes.csw.G8.medicamento.persistence.entity.MedicamentoEntity;
import co.edu.uniandes.csw.G8.medicamento.persistence.converter.MedicamentoConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class MedicamentoPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(MedicamentoPersistence.class.getPackage())
				.addPackage(MedicamentoEntity.class.getPackage())
				.addPackage(IMedicamentoPersistence.class.getPackage())
                .addPackage(MedicamentoDTO.class.getPackage())
                .addPackage(MedicamentoConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IMedicamentoPersistence medicamentoPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from MedicamentoEntity").executeUpdate();
	}

	private List<MedicamentoEntity> data=new ArrayList<MedicamentoEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			MedicamentoEntity entity=new MedicamentoEntity();
			entity.setName(generateRandom(String.class));
			entity.setDescripcion(generateRandom(String.class));
			entity.setTipo_medicamentoId(generateRandom(Long.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createMedicamentoTest(){
		MedicamentoDTO dto=new MedicamentoDTO();
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setTipo_medicamentoId(generateRandom(Long.class));
		
		MedicamentoDTO result=medicamentoPersistence.createMedicamento(dto);
		
		Assert.assertNotNull(result);
		
		MedicamentoEntity entity=em.find(MedicamentoEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getDescripcion(), entity.getDescripcion());
		Assert.assertEquals(dto.getTipo_medicamentoId(), entity.getTipo_medicamentoId());
	}
	
	@Test
	public void getMedicamentosTest(){
		List<MedicamentoDTO> list=medicamentoPersistence.getMedicamentos();
		Assert.assertEquals(list.size(), data.size());
        for(MedicamentoDTO dto:list){
        	boolean found=false;
            for(MedicamentoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getMedicamentoTest(){
		MedicamentoEntity entity=data.get(0);
		MedicamentoDTO dto=medicamentoPersistence.getMedicamento(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getDescripcion(), dto.getDescripcion());
		Assert.assertEquals(entity.getTipo_medicamentoId(), dto.getTipo_medicamentoId());
        
	}
	
	@Test
	public void deleteMedicamentoTest(){
		MedicamentoEntity entity=data.get(0);
		medicamentoPersistence.deleteMedicamento(entity.getId());
        MedicamentoEntity deleted=em.find(MedicamentoEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateMedicamentoTest(){
		MedicamentoEntity entity=data.get(0);
		
		MedicamentoDTO dto=new MedicamentoDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setDescripcion(generateRandom(String.class));
		dto.setTipo_medicamentoId(generateRandom(Long.class));
		
		
		medicamentoPersistence.updateMedicamento(dto);
		
		
		MedicamentoEntity resp=em.find(MedicamentoEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(dto.getTipo_medicamentoId(), resp.getTipo_medicamentoId());	
	}
	
	@Test
	public void getMedicamentoPaginationTest(){
		//Page 1
		MedicamentoPageDTO dto1=medicamentoPersistence.getMedicamentos(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        MedicamentoPageDTO dto2=medicamentoPersistence.getMedicamentos(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(MedicamentoDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(MedicamentoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(MedicamentoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(MedicamentoEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}