/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.paciente.master.persistence;
import co.edu.uniandes.csw.G8.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G8.paciente.master.persistence.entity.PacienteactividadEntity;
import co.edu.uniandes.csw.G8.actividad.persistence.converter.ActividadConverter;
import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioDTO;
import co.edu.uniandes.csw.G8.paciente.master.persistence.entity.PacienteepisodioEntity;
import co.edu.uniandes.csw.G8.episodio.persistence.converter.EpisodioConverter;
import co.edu.uniandes.csw.G8.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.G8.paciente.master.logic.dto.PacienteMasterDTO;
import co.edu.uniandes.csw.G8.paciente.master.persistence.api._IPacienteMasterPersistence;
import co.edu.uniandes.csw.G8.paciente.persistence.api.IPacientePersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _PacienteMasterPersistence implements _IPacienteMasterPersistence {

  	@PersistenceContext(unitName="MigrandesCrudPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IPacientePersistence pacientePersistence;  

    public PacienteMasterDTO getPaciente(Long pacienteId) {
        PacienteMasterDTO pacienteMasterDTO = new PacienteMasterDTO();
        PacienteDTO paciente = pacientePersistence.getPaciente(pacienteId);
        pacienteMasterDTO.setPacienteEntity(paciente);
        pacienteMasterDTO.setListactividad(getPacienteactividadEntityList(pacienteId));
        pacienteMasterDTO.setListepisodio(getPacienteepisodioEntityList(pacienteId));
        return pacienteMasterDTO;
    }

    public PacienteactividadEntity createPacienteactividadEntity(PacienteactividadEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deletePacienteactividadEntity(Long pacienteId, Long actividadId) {
        Query q = entityManager.createNamedQuery("PacienteactividadEntity.deletePacienteactividadEntity");
        q.setParameter("pacienteId", pacienteId);
        q.setParameter("actividadId", actividadId);
        q.executeUpdate();
    }

    public List<ActividadDTO> getPacienteactividadEntityList(Long pacienteId) {
        ArrayList<ActividadDTO> resp = new ArrayList<ActividadDTO>();
        Query q = entityManager.createNamedQuery("PacienteactividadEntity.getByMasterId");
        q.setParameter("pacienteId",pacienteId);
        List<PacienteactividadEntity> qResult =  q.getResultList();
        for (PacienteactividadEntity entity : qResult) { 
            if(entity.getActividadIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ActividadConverter.entity2PersistenceDTO(entity.getActividadIdEntity()));
        }
        return resp;
    }
    public PacienteepisodioEntity createPacienteepisodioEntity(PacienteepisodioEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deletePacienteepisodioEntity(Long pacienteId, Long episodioId) {
        Query q = entityManager.createNamedQuery("PacienteepisodioEntity.deletePacienteepisodioEntity");
        q.setParameter("pacienteId", pacienteId);
        q.setParameter("episodioId", episodioId);
        q.executeUpdate();
    }

    public List<EpisodioDTO> getPacienteepisodioEntityList(Long pacienteId) {
        ArrayList<EpisodioDTO> resp = new ArrayList<EpisodioDTO>();
        Query q = entityManager.createNamedQuery("PacienteepisodioEntity.getByMasterId");
        q.setParameter("pacienteId",pacienteId);
        List<PacienteepisodioEntity> qResult =  q.getResultList();
        for (PacienteepisodioEntity entity : qResult) { 
            if(entity.getEpisodioIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EpisodioConverter.entity2PersistenceDTO(entity.getEpisodioIdEntity()));
        }
        return resp;
    }

}
