/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.medicamento.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoDTO;
import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoPageDTO;
import co.edu.uniandes.csw.G8.medicamento.logic.api._IMedicamentoLogicService;
import co.edu.uniandes.csw.G8.medicamento.persistence.api.IMedicamentoPersistence;

public abstract class _MedicamentoLogicService implements _IMedicamentoLogicService {

	@Inject
	protected IMedicamentoPersistence persistance;

	public MedicamentoDTO createMedicamento(MedicamentoDTO medicamento){
		return persistance.createMedicamento( medicamento); 
    }

	public List<MedicamentoDTO> getMedicamentos(){
		return persistance.getMedicamentos(); 
	}

	public MedicamentoPageDTO getMedicamentos(Integer page, Integer maxRecords){
		return persistance.getMedicamentos(page, maxRecords); 
	}

	public MedicamentoDTO getMedicamento(Long id){
		return persistance.getMedicamento(id); 
	}

	public void deleteMedicamento(Long id){
	    persistance.deleteMedicamento(id); 
	}

	public void updateMedicamento(MedicamentoDTO medicamento){
	    persistance.updateMedicamento(medicamento); 
	}	
}