/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.intensidad.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadPageDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.api._IIntensidadLogicService;

public abstract class _IntensidadMockLogicService implements _IIntensidadLogicService {

	private Long id= new Long(1);
	protected List<IntensidadDTO> data=new ArrayList<IntensidadDTO>();

	public IntensidadDTO createIntensidad(IntensidadDTO intensidad){
		id++;
		intensidad.setId(id);
		data.add(intensidad);
		return intensidad;
    }
    
    public List<IntensidadDTO> getIntensidads(){
		return data; 
	}

	public IntensidadPageDTO getIntensidads(Integer page, Integer maxRecords){
		IntensidadPageDTO response = new IntensidadPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public IntensidadDTO getIntensidad(Long id){
		for(IntensidadDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteIntensidad(Long id){
	    IntensidadDTO delete=null;
		for(IntensidadDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateIntensidad(IntensidadDTO intensidad){
	    IntensidadDTO delete=null;
		for(IntensidadDTO data1:data){
			if(data1.getId().equals(intensidad.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(intensidad);
		} 
	}	
}