/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.tipo_medicamento.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoPageDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.logic.api.ITipo_MedicamentoLogicService;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.Tipo_MedicamentoPersistence;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.api.ITipo_MedicamentoPersistence;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.entity.Tipo_MedicamentoEntity;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.converter.Tipo_MedicamentoConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class Tipo_MedicamentoLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(Tipo_MedicamentoLogicService.class.getPackage())
				.addPackage(ITipo_MedicamentoLogicService.class.getPackage())
				.addPackage(Tipo_MedicamentoPersistence.class.getPackage())
				.addPackage(Tipo_MedicamentoEntity.class.getPackage())
				.addPackage(ITipo_MedicamentoPersistence.class.getPackage())
                .addPackage(Tipo_MedicamentoDTO.class.getPackage())
                .addPackage(Tipo_MedicamentoConverter.class.getPackage())
                .addPackage(Tipo_MedicamentoEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private ITipo_MedicamentoLogicService tipo_MedicamentoLogicService;
	
	@Inject
	private ITipo_MedicamentoPersistence tipo_MedicamentoPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<Tipo_MedicamentoDTO> dtos=tipo_MedicamentoPersistence.getTipo_Medicamentos();
		for(Tipo_MedicamentoDTO dto:dtos){
			tipo_MedicamentoPersistence.deleteTipo_Medicamento(dto.getId());
		}
	}

	private List<Tipo_MedicamentoDTO> data=new ArrayList<Tipo_MedicamentoDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			Tipo_MedicamentoDTO pdto=new Tipo_MedicamentoDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setValor(generateRandom(Integer.class));
			pdto=tipo_MedicamentoPersistence.createTipo_Medicamento(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createTipo_MedicamentoTest(){
		Tipo_MedicamentoDTO ldto=new Tipo_MedicamentoDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setValor(generateRandom(Integer.class));
		
		
		Tipo_MedicamentoDTO result=tipo_MedicamentoLogicService.createTipo_Medicamento(ldto);
		
		Assert.assertNotNull(result);
		
		Tipo_MedicamentoDTO pdto=tipo_MedicamentoPersistence.getTipo_Medicamento(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getValor(), pdto.getValor());	
	}
	
	@Test
	public void getTipo_MedicamentosTest(){
		List<Tipo_MedicamentoDTO> list=tipo_MedicamentoLogicService.getTipo_Medicamentos();
		Assert.assertEquals(list.size(), data.size());
        for(Tipo_MedicamentoDTO ldto:list){
        	boolean found=false;
            for(Tipo_MedicamentoDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getTipo_MedicamentoTest(){
		Tipo_MedicamentoDTO pdto=data.get(0);
		Tipo_MedicamentoDTO ldto=tipo_MedicamentoLogicService.getTipo_Medicamento(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getValor(), ldto.getValor());
        
	}
	
	@Test
	public void deleteTipo_MedicamentoTest(){
		Tipo_MedicamentoDTO pdto=data.get(0);
		tipo_MedicamentoLogicService.deleteTipo_Medicamento(pdto.getId());
        Tipo_MedicamentoDTO deleted=tipo_MedicamentoPersistence.getTipo_Medicamento(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateTipo_MedicamentoTest(){
		Tipo_MedicamentoDTO pdto=data.get(0);
		
		Tipo_MedicamentoDTO ldto=new Tipo_MedicamentoDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setValor(generateRandom(Integer.class));
		
		
		tipo_MedicamentoLogicService.updateTipo_Medicamento(ldto);
		
		
		Tipo_MedicamentoDTO resp=tipo_MedicamentoPersistence.getTipo_Medicamento(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getValor(), resp.getValor());	
	}
	
	@Test
	public void getTipo_MedicamentoPaginationTest(){
		
		Tipo_MedicamentoPageDTO dto1=tipo_MedicamentoLogicService.getTipo_Medicamentos(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		Tipo_MedicamentoPageDTO dto2=tipo_MedicamentoLogicService.getTipo_Medicamentos(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(Tipo_MedicamentoDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(Tipo_MedicamentoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(Tipo_MedicamentoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(Tipo_MedicamentoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        Tipo_MedicamentoPageDTO dto3=tipo_MedicamentoLogicService.getTipo_Medicamentos(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(Tipo_MedicamentoDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(Tipo_MedicamentoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}