/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.paciente.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.paciente.logic.dto.PacientePageDTO;
import co.edu.uniandes.csw.G8.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.G8.paciente.persistence.api.IPacientePersistence;
import co.edu.uniandes.csw.G8.paciente.persistence.entity.PacienteEntity;
import co.edu.uniandes.csw.G8.paciente.persistence.converter.PacienteConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class PacientePersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(PacientePersistence.class.getPackage())
				.addPackage(PacienteEntity.class.getPackage())
				.addPackage(IPacientePersistence.class.getPackage())
                .addPackage(PacienteDTO.class.getPackage())
                .addPackage(PacienteConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IPacientePersistence pacientePersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from PacienteEntity").executeUpdate();
	}

	private List<PacienteEntity> data=new ArrayList<PacienteEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			PacienteEntity entity=new PacienteEntity();
			entity.setName(generateRandom(String.class));
			entity.setTelefono(generateRandom(Integer.class));
			entity.setUsuario(generateRandom(String.class));
			entity.setContraseña(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createPacienteTest(){
		PacienteDTO dto=new PacienteDTO();
		dto.setName(generateRandom(String.class));
		dto.setTelefono(generateRandom(Integer.class));
		dto.setUsuario(generateRandom(String.class));
		dto.setContraseña(generateRandom(String.class));
		
		PacienteDTO result=pacientePersistence.createPaciente(dto);
		
		Assert.assertNotNull(result);
		
		PacienteEntity entity=em.find(PacienteEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getTelefono(), entity.getTelefono());
		Assert.assertEquals(dto.getUsuario(), entity.getUsuario());
		Assert.assertEquals(dto.getContraseña(), entity.getContraseña());
	}
	
	@Test
	public void getPacientesTest(){
		List<PacienteDTO> list=pacientePersistence.getPacientes();
		Assert.assertEquals(list.size(), data.size());
        for(PacienteDTO dto:list){
        	boolean found=false;
            for(PacienteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getPacienteTest(){
		PacienteEntity entity=data.get(0);
		PacienteDTO dto=pacientePersistence.getPaciente(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getTelefono(), dto.getTelefono());
		Assert.assertEquals(entity.getUsuario(), dto.getUsuario());
		Assert.assertEquals(entity.getContraseña(), dto.getContraseña());
        
	}
	
	@Test
	public void deletePacienteTest(){
		PacienteEntity entity=data.get(0);
		pacientePersistence.deletePaciente(entity.getId());
        PacienteEntity deleted=em.find(PacienteEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updatePacienteTest(){
		PacienteEntity entity=data.get(0);
		
		PacienteDTO dto=new PacienteDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setTelefono(generateRandom(Integer.class));
		dto.setUsuario(generateRandom(String.class));
		dto.setContraseña(generateRandom(String.class));
		
		
		pacientePersistence.updatePaciente(dto);
		
		
		PacienteEntity resp=em.find(PacienteEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getTelefono(), resp.getTelefono());	
		Assert.assertEquals(dto.getUsuario(), resp.getUsuario());	
		Assert.assertEquals(dto.getContraseña(), resp.getContraseña());	
	}
	
	@Test
	public void getPacientePaginationTest(){
		//Page 1
		PacientePageDTO dto1=pacientePersistence.getPacientes(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        PacientePageDTO dto2=pacientePersistence.getPacientes(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(PacienteDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(PacienteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(PacienteDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(PacienteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}