/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.notadevoz.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G8.notadevoz.logic.dto.NotaDeVozDTO;
import co.edu.uniandes.csw.G8.notadevoz.logic.dto.NotaDeVozPageDTO;
import co.edu.uniandes.csw.G8.notadevoz.logic.api._INotaDeVozLogicService;

public abstract class _NotaDeVozMockLogicService implements _INotaDeVozLogicService {

	private Long id= new Long(1);
	protected List<NotaDeVozDTO> data=new ArrayList<NotaDeVozDTO>();

	public NotaDeVozDTO createNotaDeVoz(NotaDeVozDTO notaDeVoz){
		id++;
		notaDeVoz.setId(id);
		data.add(notaDeVoz);
		return notaDeVoz;
    }
    
    public List<NotaDeVozDTO> getNotaDeVozs(){
		return data; 
	}

	public NotaDeVozPageDTO getNotaDeVozs(Integer page, Integer maxRecords){
		NotaDeVozPageDTO response = new NotaDeVozPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public NotaDeVozDTO getNotaDeVoz(Long id){
		for(NotaDeVozDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteNotaDeVoz(Long id){
	    NotaDeVozDTO delete=null;
		for(NotaDeVozDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateNotaDeVoz(NotaDeVozDTO notaDeVoz){
	    NotaDeVozDTO delete=null;
		for(NotaDeVozDTO data1:data){
			if(data1.getId().equals(notaDeVoz.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(notaDeVoz);
		} 
	}	
}