/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.intensidad.logic.ejb;
import java.util.List;
import javax.inject.Inject;

import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadPageDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.api._IIntensidadLogicService;
import co.edu.uniandes.csw.G8.intensidad.persistence.api.IIntensidadPersistence;

public abstract class _IntensidadLogicService implements _IIntensidadLogicService {

	@Inject
	protected IIntensidadPersistence persistance;

	public IntensidadDTO createIntensidad(IntensidadDTO intensidad){
		return persistance.createIntensidad( intensidad); 
    }

	public List<IntensidadDTO> getIntensidads(){
		return persistance.getIntensidads(); 
	}

	public IntensidadPageDTO getIntensidads(Integer page, Integer maxRecords){
		return persistance.getIntensidads(page, maxRecords); 
	}

	public IntensidadDTO getIntensidad(Long id){
		return persistance.getIntensidad(id); 
	}

	public void deleteIntensidad(Long id){
	    persistance.deleteIntensidad(id); 
	}

	public void updateIntensidad(IntensidadDTO intensidad){
	    persistance.updateIntensidad(intensidad); 
	}	
}