/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.paciente.master.logic.ejb;

import co.edu.uniandes.csw.G8.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G8.actividad.persistence.api.IActividadPersistence;
import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioDTO;
import co.edu.uniandes.csw.G8.episodio.persistence.api.IEpisodioPersistence;
import co.edu.uniandes.csw.G8.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.G8.paciente.master.logic.api._IPacienteMasterLogicService;
import co.edu.uniandes.csw.G8.paciente.master.logic.dto.PacienteMasterDTO;
import co.edu.uniandes.csw.G8.paciente.master.persistence.api.IPacienteMasterPersistence;
import co.edu.uniandes.csw.G8.paciente.master.persistence.entity.PacienteactividadEntity;
import co.edu.uniandes.csw.G8.paciente.master.persistence.entity.PacienteepisodioEntity;
import co.edu.uniandes.csw.G8.paciente.persistence.api.IPacientePersistence;
import javax.inject.Inject;

public abstract class _PacienteMasterLogicService implements _IPacienteMasterLogicService {

    @Inject
    protected IPacientePersistence pacientePersistance;
    @Inject
    protected IPacienteMasterPersistence pacienteMasterPersistance;
    @Inject
    protected IActividadPersistence actividadPersistance;
    @Inject
    protected IEpisodioPersistence episodioPersistance;

    public PacienteMasterDTO createMasterPaciente(PacienteMasterDTO paciente) {
        PacienteDTO persistedPacienteDTO = pacientePersistance.createPaciente(paciente.getPacienteEntity());
        if (paciente.getCreateactividad() != null) {
            for (ActividadDTO actividadDTO : paciente.getCreateactividad()) {
                ActividadDTO createdActividadDTO = actividadPersistance.createActividad(actividadDTO);
                PacienteactividadEntity pacienteActividadEntity = new PacienteactividadEntity(persistedPacienteDTO.getId(), createdActividadDTO.getId());
                pacienteMasterPersistance.createPacienteactividadEntity(pacienteActividadEntity);
            }
        }
        if (paciente.getCreateepisodio() != null) {
            for (EpisodioDTO episodioDTO : paciente.getCreateepisodio()) {
                EpisodioDTO createdEpisodioDTO = episodioPersistance.createEpisodio(episodioDTO);
                PacienteepisodioEntity pacienteEpisodioEntity = new PacienteepisodioEntity(persistedPacienteDTO.getId(), createdEpisodioDTO.getId());
                pacienteMasterPersistance.createPacienteepisodioEntity(pacienteEpisodioEntity);
            }
        }
        // update actividad
        if (paciente.getUpdateactividad() != null) {
            for (ActividadDTO actividadDTO : paciente.getUpdateactividad()) {
                actividadPersistance.updateActividad(actividadDTO);
                PacienteactividadEntity pacienteActividadEntity = new PacienteactividadEntity(persistedPacienteDTO.getId(), actividadDTO.getId());
                pacienteMasterPersistance.createPacienteactividadEntity(pacienteActividadEntity);
            }
        }
        // update episodio
        if (paciente.getUpdateepisodio() != null) {
            for (EpisodioDTO episodioDTO : paciente.getUpdateepisodio()) {
                episodioPersistance.updateEpisodio(episodioDTO);
                PacienteepisodioEntity pacienteEpisodioEntity = new PacienteepisodioEntity(persistedPacienteDTO.getId(), episodioDTO.getId());
                pacienteMasterPersistance.createPacienteepisodioEntity(pacienteEpisodioEntity);
            }
        }
        return paciente;
    }

    public PacienteMasterDTO getMasterPaciente(Long id) {
        return pacienteMasterPersistance.getPaciente(id);
    }

    public void deleteMasterPaciente(Long id) {
        pacientePersistance.deletePaciente(id);
    }

    public void updateMasterPaciente(PacienteMasterDTO paciente) {
        pacientePersistance.updatePaciente(paciente.getPacienteEntity());

        //---- FOR RELATIONSHIP
        // persist new actividad
        if (paciente.getCreateactividad() != null) {
            for (ActividadDTO actividadDTO : paciente.getCreateactividad()) {
                ActividadDTO createdActividadDTO = actividadPersistance.createActividad(actividadDTO);
                PacienteactividadEntity pacienteActividadEntity = new PacienteactividadEntity(paciente.getPacienteEntity().getId(), createdActividadDTO.getId());
                pacienteMasterPersistance.createPacienteactividadEntity(pacienteActividadEntity);
            }
        }
        // update actividad
        if (paciente.getUpdateactividad() != null) {
            for (ActividadDTO actividadDTO : paciente.getUpdateactividad()) {
                actividadPersistance.updateActividad(actividadDTO);
            }
        }
        // delete actividad
        if (paciente.getDeleteactividad() != null) {
            for (ActividadDTO actividadDTO : paciente.getDeleteactividad()) {
                pacienteMasterPersistance.deletePacienteactividadEntity(paciente.getPacienteEntity().getId(), actividadDTO.getId());
                actividadPersistance.deleteActividad(actividadDTO.getId());
            }
        }
        // persist new episodio
        if (paciente.getCreateepisodio() != null) {
            for (EpisodioDTO episodioDTO : paciente.getCreateepisodio()) {
                EpisodioDTO createdEpisodioDTO = episodioPersistance.createEpisodio(episodioDTO);
                PacienteepisodioEntity pacienteEpisodioEntity = new PacienteepisodioEntity(paciente.getPacienteEntity().getId(), createdEpisodioDTO.getId());
                pacienteMasterPersistance.createPacienteepisodioEntity(pacienteEpisodioEntity);
            }
        }
        // update episodio
        if (paciente.getUpdateepisodio() != null) {
            for (EpisodioDTO episodioDTO : paciente.getUpdateepisodio()) {
                episodioPersistance.updateEpisodio(episodioDTO);
            }
        }
        // delete episodio
        if (paciente.getDeleteepisodio() != null) {
            for (EpisodioDTO episodioDTO : paciente.getDeleteepisodio()) {
                pacienteMasterPersistance.deletePacienteepisodioEntity(paciente.getPacienteEntity().getId(), episodioDTO.getId());
                episodioPersistance.deleteEpisodio(episodioDTO.getId());
            }
        }
    }
}
