/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.tipo_medicamento.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoPageDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.api._ITipo_MedicamentoPersistence;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.converter.Tipo_MedicamentoConverter;
import co.edu.uniandes.csw.G8.tipo_medicamento.persistence.entity.Tipo_MedicamentoEntity;

public abstract class _Tipo_MedicamentoPersistence implements _ITipo_MedicamentoPersistence {

  	@PersistenceContext(unitName="MigrandesCrudPU")
 
	protected EntityManager entityManager;
	
	public Tipo_MedicamentoDTO createTipo_Medicamento(Tipo_MedicamentoDTO tipo_Medicamento) {
		Tipo_MedicamentoEntity entity=Tipo_MedicamentoConverter.persistenceDTO2Entity(tipo_Medicamento);
		entityManager.persist(entity);
		return Tipo_MedicamentoConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<Tipo_MedicamentoDTO> getTipo_Medicamentos() {
		Query q = entityManager.createQuery("select u from Tipo_MedicamentoEntity u");
		return Tipo_MedicamentoConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public Tipo_MedicamentoPageDTO getTipo_Medicamentos(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from Tipo_MedicamentoEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from Tipo_MedicamentoEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		Tipo_MedicamentoPageDTO response = new Tipo_MedicamentoPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(Tipo_MedicamentoConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public Tipo_MedicamentoDTO getTipo_Medicamento(Long id) {
		return Tipo_MedicamentoConverter.entity2PersistenceDTO(entityManager.find(Tipo_MedicamentoEntity.class, id));
	}

	public void deleteTipo_Medicamento(Long id) {
		Tipo_MedicamentoEntity entity=entityManager.find(Tipo_MedicamentoEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateTipo_Medicamento(Tipo_MedicamentoDTO detail) {
		Tipo_MedicamentoEntity entity=entityManager.merge(Tipo_MedicamentoConverter.persistenceDTO2Entity(detail));
		Tipo_MedicamentoConverter.entity2PersistenceDTO(entity);
	}

}