/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.tipo_medicamento.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.logic.dto.Tipo_MedicamentoPageDTO;
import co.edu.uniandes.csw.G8.tipo_medicamento.logic.api._ITipo_MedicamentoLogicService;

public abstract class _Tipo_MedicamentoMockLogicService implements _ITipo_MedicamentoLogicService {

	private Long id= new Long(1);
	protected List<Tipo_MedicamentoDTO> data=new ArrayList<Tipo_MedicamentoDTO>();

	public Tipo_MedicamentoDTO createTipo_Medicamento(Tipo_MedicamentoDTO tipo_Medicamento){
		id++;
		tipo_Medicamento.setId(id);
		data.add(tipo_Medicamento);
		return tipo_Medicamento;
    }
    
    public List<Tipo_MedicamentoDTO> getTipo_Medicamentos(){
		return data; 
	}

	public Tipo_MedicamentoPageDTO getTipo_Medicamentos(Integer page, Integer maxRecords){
		Tipo_MedicamentoPageDTO response = new Tipo_MedicamentoPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public Tipo_MedicamentoDTO getTipo_Medicamento(Long id){
		for(Tipo_MedicamentoDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteTipo_Medicamento(Long id){
	    Tipo_MedicamentoDTO delete=null;
		for(Tipo_MedicamentoDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateTipo_Medicamento(Tipo_MedicamentoDTO tipo_Medicamento){
	    Tipo_MedicamentoDTO delete=null;
		for(Tipo_MedicamentoDTO data1:data){
			if(data1.getId().equals(tipo_Medicamento.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(tipo_Medicamento);
		} 
	}	
}