/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.medicamento.logic.ejb;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoPageDTO;
import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoDTO;
import co.edu.uniandes.csw.G8.medicamento.logic.api.IMedicamentoLogicService;
import co.edu.uniandes.csw.G8.medicamento.persistence.MedicamentoPersistence;
import co.edu.uniandes.csw.G8.medicamento.persistence.api.IMedicamentoPersistence;
import co.edu.uniandes.csw.G8.medicamento.persistence.entity.MedicamentoEntity;
import co.edu.uniandes.csw.G8.medicamento.persistence.converter.MedicamentoConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class MedicamentoLogicServiceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(MedicamentoLogicService.class.getPackage())
				.addPackage(IMedicamentoLogicService.class.getPackage())
				.addPackage(MedicamentoPersistence.class.getPackage())
				.addPackage(MedicamentoEntity.class.getPackage())
				.addPackage(IMedicamentoPersistence.class.getPackage())
                .addPackage(MedicamentoDTO.class.getPackage())
                .addPackage(MedicamentoConverter.class.getPackage())
                .addPackage(MedicamentoEntity.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IMedicamentoLogicService medicamentoLogicService;
	
	@Inject
	private IMedicamentoPersistence medicamentoPersistence;	

	@Before
	public void configTest() {
		try {
			clearData();
			insertData();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void clearData() {
		List<MedicamentoDTO> dtos=medicamentoPersistence.getMedicamentos();
		for(MedicamentoDTO dto:dtos){
			medicamentoPersistence.deleteMedicamento(dto.getId());
		}
	}

	private List<MedicamentoDTO> data=new ArrayList<MedicamentoDTO>();

	private void insertData() {
		for(int i=0;i<3;i++){
			MedicamentoDTO pdto=new MedicamentoDTO();
			pdto.setName(generateRandom(String.class));
			pdto.setDescripcion(generateRandom(String.class));
			pdto.setTipo_medicamentoId(generateRandom(Long.class));
			pdto=medicamentoPersistence.createMedicamento(pdto);
			data.add(pdto);
		}
	}
	
	@Test
	public void createMedicamentoTest(){
		MedicamentoDTO ldto=new MedicamentoDTO();
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setTipo_medicamentoId(generateRandom(Long.class));
		
		
		MedicamentoDTO result=medicamentoLogicService.createMedicamento(ldto);
		
		Assert.assertNotNull(result);
		
		MedicamentoDTO pdto=medicamentoPersistence.getMedicamento(result.getId());
		
		Assert.assertEquals(ldto.getName(), pdto.getName());	
		Assert.assertEquals(ldto.getDescripcion(), pdto.getDescripcion());	
		Assert.assertEquals(ldto.getTipo_medicamentoId(), pdto.getTipo_medicamentoId());	
	}
	
	@Test
	public void getMedicamentosTest(){
		List<MedicamentoDTO> list=medicamentoLogicService.getMedicamentos();
		Assert.assertEquals(list.size(), data.size());
        for(MedicamentoDTO ldto:list){
        	boolean found=false;
            for(MedicamentoDTO pdto:data){
            	if(ldto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getMedicamentoTest(){
		MedicamentoDTO pdto=data.get(0);
		MedicamentoDTO ldto=medicamentoLogicService.getMedicamento(pdto.getId());
        Assert.assertNotNull(ldto);
		Assert.assertEquals(pdto.getName(), ldto.getName());
		Assert.assertEquals(pdto.getDescripcion(), ldto.getDescripcion());
		Assert.assertEquals(pdto.getTipo_medicamentoId(), ldto.getTipo_medicamentoId());
        
	}
	
	@Test
	public void deleteMedicamentoTest(){
		MedicamentoDTO pdto=data.get(0);
		medicamentoLogicService.deleteMedicamento(pdto.getId());
        MedicamentoDTO deleted=medicamentoPersistence.getMedicamento(pdto.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateMedicamentoTest(){
		MedicamentoDTO pdto=data.get(0);
		
		MedicamentoDTO ldto=new MedicamentoDTO();
		ldto.setId(pdto.getId());
		ldto.setName(generateRandom(String.class));
		ldto.setDescripcion(generateRandom(String.class));
		ldto.setTipo_medicamentoId(generateRandom(Long.class));
		
		
		medicamentoLogicService.updateMedicamento(ldto);
		
		
		MedicamentoDTO resp=medicamentoPersistence.getMedicamento(pdto.getId());
		
		Assert.assertEquals(ldto.getName(), resp.getName());	
		Assert.assertEquals(ldto.getDescripcion(), resp.getDescripcion());	
		Assert.assertEquals(ldto.getTipo_medicamentoId(), resp.getTipo_medicamentoId());	
	}
	
	@Test
	public void getMedicamentoPaginationTest(){
		
		MedicamentoPageDTO dto1=medicamentoLogicService.getMedicamentos(1,2);
		Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
		
		
		MedicamentoPageDTO dto2=medicamentoLogicService.getMedicamentos(2,2);
		Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
		
		for(MedicamentoDTO dto:dto1.getRecords()){
        	boolean found=false;
            for(MedicamentoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(MedicamentoDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(MedicamentoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        MedicamentoPageDTO dto3=medicamentoLogicService.getMedicamentos(1,3);
		Assert.assertNotNull(dto3);
        Assert.assertEquals(dto3.getRecords().size(),data.size());
        Assert.assertEquals(dto3.getTotalRecords().longValue(),data.size());
		
		for(MedicamentoDTO dto:dto3.getRecords()){
        	boolean found=false;
            for(MedicamentoDTO pdto:data){
            	if(dto.getId()==pdto.getId()){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	
}