/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.dolor.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.G8.dolor.logic.dto.DolorDTO;
import co.edu.uniandes.csw.G8.dolor.logic.dto.DolorPageDTO;
import co.edu.uniandes.csw.G8.dolor.logic.api._IDolorLogicService;

public abstract class _DolorMockLogicService implements _IDolorLogicService {

	private Long id= new Long(1);
	protected List<DolorDTO> data=new ArrayList<DolorDTO>();

	public DolorDTO createDolor(DolorDTO dolor){
		id++;
		dolor.setId(id);
		data.add(dolor);
		return dolor;
    }
    
    public List<DolorDTO> getDolors(){
		return data; 
	}

	public DolorPageDTO getDolors(Integer page, Integer maxRecords){
		DolorPageDTO response = new DolorPageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public DolorDTO getDolor(Long id){
		for(DolorDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteDolor(Long id){
	    DolorDTO delete=null;
		for(DolorDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateDolor(DolorDTO dolor){
	    DolorDTO delete=null;
		for(DolorDTO data1:data){
			if(data1.getId().equals(dolor.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(dolor);
		} 
	}	
}