/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.intensidad.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadPageDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadDTO;
import co.edu.uniandes.csw.G8.intensidad.persistence.api.IIntensidadPersistence;
import co.edu.uniandes.csw.G8.intensidad.persistence.entity.IntensidadEntity;
import co.edu.uniandes.csw.G8.intensidad.persistence.converter.IntensidadConverter;
import static co.edu.uniandes.csw.G8.util._TestUtil.*;

@RunWith(Arquillian.class)
public class IntensidadPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(IntensidadPersistence.class.getPackage())
				.addPackage(IntensidadEntity.class.getPackage())
				.addPackage(IIntensidadPersistence.class.getPackage())
                .addPackage(IntensidadDTO.class.getPackage())
                .addPackage(IntensidadConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IIntensidadPersistence intensidadPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from IntensidadEntity").executeUpdate();
	}

	private List<IntensidadEntity> data=new ArrayList<IntensidadEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			IntensidadEntity entity=new IntensidadEntity();
			entity.setName(generateRandom(String.class));
			entity.setValor(generateRandom(Integer.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createIntensidadTest(){
		IntensidadDTO dto=new IntensidadDTO();
		dto.setName(generateRandom(String.class));
		dto.setValor(generateRandom(Integer.class));
		
		IntensidadDTO result=intensidadPersistence.createIntensidad(dto);
		
		Assert.assertNotNull(result);
		
		IntensidadEntity entity=em.find(IntensidadEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getValor(), entity.getValor());
	}
	
	@Test
	public void getIntensidadsTest(){
		List<IntensidadDTO> list=intensidadPersistence.getIntensidads();
		Assert.assertEquals(list.size(), data.size());
        for(IntensidadDTO dto:list){
        	boolean found=false;
            for(IntensidadEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getIntensidadTest(){
		IntensidadEntity entity=data.get(0);
		IntensidadDTO dto=intensidadPersistence.getIntensidad(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getValor(), dto.getValor());
        
	}
	
	@Test
	public void deleteIntensidadTest(){
		IntensidadEntity entity=data.get(0);
		intensidadPersistence.deleteIntensidad(entity.getId());
        IntensidadEntity deleted=em.find(IntensidadEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateIntensidadTest(){
		IntensidadEntity entity=data.get(0);
		
		IntensidadDTO dto=new IntensidadDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setValor(generateRandom(Integer.class));
		
		
		intensidadPersistence.updateIntensidad(dto);
		
		
		IntensidadEntity resp=em.find(IntensidadEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getValor(), resp.getValor());	
	}
	
	@Test
	public void getIntensidadPaginationTest(){
		//Page 1
		IntensidadPageDTO dto1=intensidadPersistence.getIntensidads(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        IntensidadPageDTO dto2=intensidadPersistence.getIntensidads(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(IntensidadDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(IntensidadEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(IntensidadDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(IntensidadEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}