/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.intensidad.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadDTO;
import co.edu.uniandes.csw.G8.intensidad.logic.dto.IntensidadPageDTO;
import co.edu.uniandes.csw.G8.intensidad.persistence.api._IIntensidadPersistence;
import co.edu.uniandes.csw.G8.intensidad.persistence.converter.IntensidadConverter;
import co.edu.uniandes.csw.G8.intensidad.persistence.entity.IntensidadEntity;

public abstract class _IntensidadPersistence implements _IIntensidadPersistence {

  	@PersistenceContext(unitName="MigrandesCrudPU")
 
	protected EntityManager entityManager;
	
	public IntensidadDTO createIntensidad(IntensidadDTO intensidad) {
		IntensidadEntity entity=IntensidadConverter.persistenceDTO2Entity(intensidad);
		entityManager.persist(entity);
		return IntensidadConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<IntensidadDTO> getIntensidads() {
		Query q = entityManager.createQuery("select u from IntensidadEntity u");
		return IntensidadConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public IntensidadPageDTO getIntensidads(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from IntensidadEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from IntensidadEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		IntensidadPageDTO response = new IntensidadPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(IntensidadConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public IntensidadDTO getIntensidad(Long id) {
		return IntensidadConverter.entity2PersistenceDTO(entityManager.find(IntensidadEntity.class, id));
	}

	public void deleteIntensidad(Long id) {
		IntensidadEntity entity=entityManager.find(IntensidadEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateIntensidad(IntensidadDTO detail) {
		IntensidadEntity entity=entityManager.merge(IntensidadConverter.persistenceDTO2Entity(detail));
		IntensidadConverter.entity2PersistenceDTO(entity);
	}

}