/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.paciente.master.logic.dto;

import co.edu.uniandes.csw.G8.actividad.logic.dto.ActividadDTO;
import co.edu.uniandes.csw.G8.episodio.logic.dto.EpisodioDTO;
import co.edu.uniandes.csw.G8.paciente.logic.dto.PacienteDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _PacienteMasterDTO {

 
    protected PacienteDTO pacienteEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public PacienteDTO getPacienteEntity() {
        return pacienteEntity;
    }

    public void setPacienteEntity(PacienteDTO pacienteEntity) {
        this.pacienteEntity = pacienteEntity;
    }
    
    public List<ActividadDTO> createactividad;
    public List<ActividadDTO> updateactividad;
    public List<ActividadDTO> deleteactividad;
    public List<ActividadDTO> listactividad;	
    public List<EpisodioDTO> createepisodio;
    public List<EpisodioDTO> updateepisodio;
    public List<EpisodioDTO> deleteepisodio;
    public List<EpisodioDTO> listepisodio;	
	
	
	
    public List<ActividadDTO> getCreateactividad(){ return createactividad; };
    public void setCreateactividad(List<ActividadDTO> createactividad){ this.createactividad=createactividad; };
    public List<ActividadDTO> getUpdateactividad(){ return updateactividad; };
    public void setUpdateactividad(List<ActividadDTO> updateactividad){ this.updateactividad=updateactividad; };
    public List<ActividadDTO> getDeleteactividad(){ return deleteactividad; };
    public void setDeleteactividad(List<ActividadDTO> deleteactividad){ this.deleteactividad=deleteactividad; };
    public List<ActividadDTO> getListactividad(){ return listactividad; };
    public void setListactividad(List<ActividadDTO> listactividad){ this.listactividad=listactividad; };	
    public List<EpisodioDTO> getCreateepisodio(){ return createepisodio; };
    public void setCreateepisodio(List<EpisodioDTO> createepisodio){ this.createepisodio=createepisodio; };
    public List<EpisodioDTO> getUpdateepisodio(){ return updateepisodio; };
    public void setUpdateepisodio(List<EpisodioDTO> updateepisodio){ this.updateepisodio=updateepisodio; };
    public List<EpisodioDTO> getDeleteepisodio(){ return deleteepisodio; };
    public void setDeleteepisodio(List<EpisodioDTO> deleteepisodio){ this.deleteepisodio=deleteepisodio; };
    public List<EpisodioDTO> getListepisodio(){ return listepisodio; };
    public void setListepisodio(List<EpisodioDTO> listepisodio){ this.listepisodio=listepisodio; };	
	
	
}

