/* ========================================================================
 * Copyright 2014 G8
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 G8

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.G8.medicamento.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.G8.medicamento.logic.dto.MedicamentoDTO;
import co.edu.uniandes.csw.G8.medicamento.persistence.entity.MedicamentoEntity;

public abstract class _MedicamentoConverter {

	public static MedicamentoDTO entity2PersistenceDTO(MedicamentoEntity entity){
		if (entity != null) {
			MedicamentoDTO dto = new MedicamentoDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setDescripcion(entity.getDescripcion());
					dto.setTipo_medicamentoId(entity.getTipo_medicamentoId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static MedicamentoEntity persistenceDTO2Entity(MedicamentoDTO dto){
		if(dto!=null){
			MedicamentoEntity entity=new MedicamentoEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setDescripcion(dto.getDescripcion());
			
					entity.setTipo_medicamentoId(dto.getTipo_medicamentoId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<MedicamentoDTO> entity2PersistenceDTOList(List<MedicamentoEntity> entities){
		List<MedicamentoDTO> dtos=new ArrayList<MedicamentoDTO>();
		for(MedicamentoEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<MedicamentoEntity> persistenceDTO2EntityList(List<MedicamentoDTO> dtos){
		List<MedicamentoEntity> entities=new ArrayList<MedicamentoEntity>();
		for(MedicamentoDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}